sudo: required
services:
  - docker

before_install:
  - docker build -t codingtutorial01/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true codingtutorial01/docker-react npm run test